
import { Problem } from './types';

export const CATEGORIES = ['Social', 'Environmental', 'Health', 'Education', 'Technology', 'Economy'] as const;

export const INITIAL_PROBLEMS: Problem[] = [
  // ENVIRONMENTAL
  {
    id: '1',
    title: 'Rapid Microplastic Accumulation in Coastal Fisheries',
    summary: 'Higher than normal concentrations of microplastics detected in local seafood chains, threatening food security and marine ecosystems.',
    category: 'Environmental',
    location: 'Global / Coastal Regions',
    severity: 'Critical',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 94,
    rootCause: 'Poor industrial waste management and high consumer plastic usage.',
    whoIsAffected: 'Coastal communities, seafood consumers, and marine biodiversity.',
    whyItMatters: 'Endangers long-term food safety and could lead to total ecosystem collapse.',
    impactScore: 88,
    trend: [45, 50, 65, 75, 82, 88, 92],
    thresholdLevel: 85,
    affectedPopulation: '500M+',
    upvotes: 1240,
    comments: [],
    solutionIdeas: ['Biodegradable net alternatives', 'Advanced filtration for industrial outfalls'],
    tags: ['Marine Life', 'Health', 'Waste Management'],
    timestamp: '2025-10-01T10:00:00Z',
    stakeholders: [{ name: 'Ministry of Environment', type: 'Government', role: 'Regulatory oversight', responseTime: '4.2h' }],
    timeline: [{ date: '2024-03-15', event: 'Cross-verified by satellite data', status: 'Escalating' }]
  },
  {
    id: '2',
    title: 'Urban Heat Island Intensification',
    summary: 'Concrete-heavy metropolitan areas are experiencing temperatures up to 7°C higher than surrounding areas.',
    category: 'Environmental',
    location: 'Metropolitan Areas',
    severity: 'High',
    lifecycle: 'Emerging',
    credibility: 'Partially Verified',
    credibilityScore: 78,
    rootCause: 'Lack of green space and high thermal mass of urban materials.',
    whoIsAffected: 'Urban residents, particularly elderly and low-income populations.',
    whyItMatters: 'Increases mortality rates and skyrocketing energy demand.',
    impactScore: 78,
    trend: [30, 45, 55, 68, 72, 75, 78],
    thresholdLevel: 62,
    affectedPopulation: '1.2B',
    upvotes: 890,
    comments: [],
    solutionIdeas: ['Vertical gardens', 'Reflective roofing'],
    tags: ['Climate Change', 'Urban Planning'],
    timestamp: '2025-10-05T12:00:00Z',
    stakeholders: [{ name: 'City Municipal Corporation', type: 'Government', role: 'Planning', responseTime: '12h' }],
    timeline: [{ date: '2024-02-01', event: 'Unusual heat spike noted', status: 'Emerging' }]
  },
  {
    id: '3',
    title: 'Deforestation in Protected Amazon Corridors',
    summary: 'Satellite data indicates 15% increase in illegal logging within indigenous-protected territories.',
    category: 'Environmental',
    location: 'Amazon Basin',
    severity: 'Critical',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 98,
    rootCause: 'Weak enforcement and economic pressure for agricultural land.',
    whoIsAffected: 'Indigenous tribes, global climate, biodiversity.',
    whyItMatters: 'Loss of critical carbon sink and biodiversity.',
    impactScore: 95,
    trend: [50, 60, 70, 80, 90, 95],
    thresholdLevel: 92,
    affectedPopulation: 'Global',
    upvotes: 4500,
    comments: [],
    solutionIdeas: ['AI-powered acoustic monitoring', 'Sustainable land use subsidies'],
    tags: ['Rainforest', 'Climate', 'Human Rights'],
    timestamp: '2025-11-01T08:00:00Z',
    stakeholders: [{ name: 'Global Green Alliance', type: 'NGO', role: 'Advocacy', responseTime: '1h' }],
    timeline: [{ date: '2024-05-01', event: 'Logging spike detected', status: 'Escalating' }]
  },

  // SOCIAL
  {
    id: '4',
    title: 'Systemic Youth Unemployment in Emerging Tech Hubs',
    summary: 'Mismatch between local education and industry requirements leading to 40% unemployment in skilled youth.',
    category: 'Social',
    location: 'Southeast Asia',
    severity: 'High',
    lifecycle: 'Stabilizing',
    credibility: 'Verified',
    credibilityScore: 85,
    rootCause: 'Outdated university curricula and lack of vocational training.',
    whoIsAffected: 'College graduates (ages 20-25).',
    whyItMatters: 'Could lead to social unrest and brain drain.',
    impactScore: 72,
    trend: [60, 65, 70, 72, 72, 70],
    thresholdLevel: 55,
    affectedPopulation: '25M',
    upvotes: 320,
    comments: [],
    solutionIdeas: ['Industry-integrated degrees', 'Micro-credential platform'],
    tags: ['Labor', 'Economy', 'Education'],
    timestamp: '2025-10-10T14:30:00Z',
    stakeholders: [{ name: 'Labor Ministry', type: 'Government', role: 'Policy', responseTime: '48h' }],
    timeline: [{ date: '2024-01-10', event: 'Census data published', status: 'Emerging' }]
  },
  {
    id: '5',
    title: 'The "Invisible" Digital Divide in Rural Schools',
    summary: '30% of students in rural areas lack high-speed internet, preventing participation in modern digital education.',
    category: 'Social',
    location: 'South Asia / Sub-Saharan Africa',
    severity: 'Medium',
    lifecycle: 'Emerging',
    credibility: 'Verified',
    credibilityScore: 90,
    rootCause: 'High infrastructure costs for low-density areas.',
    whoIsAffected: 'K-12 students in remote regions.',
    whyItMatters: 'Deepens inequality and limits economic mobility.',
    impactScore: 65,
    trend: [40, 45, 50, 55, 60, 65],
    thresholdLevel: 45,
    affectedPopulation: '150M',
    upvotes: 560,
    comments: [],
    solutionIdeas: ['Satellite internet subsidies', 'Community mesh networks'],
    tags: ['Equality', 'Tech Access', 'Youth'],
    timestamp: '2025-09-20T11:15:00Z',
    stakeholders: [{ name: 'EduConnect NGO', type: 'NGO', role: 'Deployment', responseTime: '6h' }],
    timeline: [{ date: '2023-12-01', event: 'Survey results analyzed', status: 'Emerging' }]
  },
  {
    id: '6',
    title: 'Elderly Isolation in Aging Urban Societies',
    summary: 'Rising rates of extreme social isolation among seniors living alone in large cities.',
    category: 'Social',
    location: 'East Asia',
    severity: 'Medium',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 88,
    rootCause: 'Breakdown of traditional multi-generational family structures.',
    whoIsAffected: 'Citizens aged 65+.',
    whyItMatters: 'Linked to severe mental health issues and early mortality.',
    impactScore: 58,
    trend: [30, 35, 42, 48, 55, 58],
    thresholdLevel: 50,
    affectedPopulation: '80M',
    upvotes: 210,
    comments: [],
    solutionIdeas: ['Intergenerational co-living', 'Community companion apps'],
    tags: ['Aging', 'Wellness', 'City Life'],
    timestamp: '2025-08-15T16:00:00Z',
    stakeholders: [{ name: 'Senior Support Net', type: 'NGO', role: 'Support', responseTime: '12h' }],
    timeline: [{ date: '2023-11-15', event: 'Social study released', status: 'Emerging' }]
  },

  // HEALTH
  {
    id: '7',
    title: 'Multidrug-Resistant Tuberculosis Surge',
    summary: 'Strains of TB resistant to standard antibiotics detected in urban dense settlements.',
    category: 'Health',
    location: 'Central Africa',
    severity: 'Critical',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 96,
    rootCause: 'Incomplete treatment courses and lack of advanced diagnostics.',
    whoIsAffected: 'Low-income urban populations.',
    whyItMatters: 'Global health security risk; could become untreatable.',
    impactScore: 92,
    trend: [40, 55, 68, 80, 88, 92],
    thresholdLevel: 88,
    affectedPopulation: '5M+',
    upvotes: 1100,
    comments: [],
    solutionIdeas: ['AI-powered treatment tracking', 'New point-of-care diagnostics'],
    tags: ['Pandemic Risk', 'Antibiotics', 'Safety'],
    timestamp: '2025-11-12T09:00:00Z',
    stakeholders: [{ name: 'WHO Regional Office', type: 'Expert', role: 'Guidance', responseTime: '0.5h' }],
    timeline: [{ date: '2024-04-01', event: 'New cases verified', status: 'Escalating' }]
  },
  {
    id: '8',
    title: 'Mental Health Crisis in Secondary Schools',
    summary: '60% increase in anxiety and depression reports among students in high-pressure school environments.',
    category: 'Health',
    location: 'Global / Urban',
    severity: 'High',
    lifecycle: 'Emerging',
    credibility: 'Verified',
    credibilityScore: 82,
    rootCause: 'Academic pressure and unregulated social media usage.',
    whoIsAffected: 'Teenagers (13-18).',
    whyItMatters: 'Long-term developmental and societal impact.',
    impactScore: 75,
    trend: [20, 35, 50, 65, 75],
    thresholdLevel: 68,
    affectedPopulation: '300M',
    upvotes: 940,
    comments: [],
    solutionIdeas: ['Peer-support platforms', 'Mandatory wellness breaks'],
    tags: ['Wellness', 'Education', 'Mental Health'],
    timestamp: '2025-10-25T13:45:00Z',
    stakeholders: [{ name: 'Global Wellness Fund', type: 'NGO', role: 'Funding', responseTime: '24h' }],
    timeline: [{ date: '2024-02-25', event: 'Survey results peak', status: 'Emerging' }]
  },
  {
    id: '9',
    title: 'Supply Chain Fragility in Life-Saving Insulin',
    summary: 'Cold-chain logistics failures causing 15% wastage of insulin in tropical regions.',
    category: 'Health',
    location: 'Tropical Global South',
    severity: 'High',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 91,
    rootCause: 'Inconsistent power grids for refrigeration.',
    whoIsAffected: 'Type-1 Diabetics.',
    whyItMatters: 'Life-critical supply gap.',
    impactScore: 82,
    trend: [50, 55, 65, 75, 82],
    thresholdLevel: 75,
    affectedPopulation: '40M',
    upvotes: 680,
    comments: [],
    solutionIdeas: ['Solar-powered portable cooling', 'Thermo-stable insulin research'],
    tags: ['Logistics', 'Diabetes', 'Energy'],
    timestamp: '2025-11-05T10:30:00Z',
    stakeholders: [{ name: 'Health Logistics Corp', type: 'Startup', role: 'Technology', responseTime: '4h' }],
    timeline: [{ date: '2024-03-05', event: 'Audit report released', status: 'Escalating' }]
  },

  // EDUCATION
  {
    id: '10',
    title: 'The STEM Gender Gap in Vocational Training',
    summary: 'Female enrollment in technical robotics and AI vocational courses remains under 10%.',
    category: 'Education',
    location: 'Central Europe',
    severity: 'Medium',
    lifecycle: 'Stabilizing',
    credibility: 'Verified',
    credibilityScore: 88,
    rootCause: 'Cultural stereotypes and lack of female mentorship.',
    whoIsAffected: 'Women entering the tech workforce.',
    whyItMatters: 'Limits innovation diversity and future economic potential.',
    impactScore: 55,
    trend: [45, 48, 52, 55, 55, 55],
    thresholdLevel: 30,
    affectedPopulation: '12M',
    upvotes: 430,
    comments: [],
    solutionIdeas: ['Diversity-focused scholarships', 'Mentorship matching AI'],
    tags: ['Equality', 'STEM', 'Workforce'],
    timestamp: '2025-09-12T08:00:00Z',
    stakeholders: [{ name: 'TechWomen Global', type: 'NGO', role: 'Mentoring', responseTime: '8h' }],
    timeline: [{ date: '2023-12-12', event: 'Study findings noted', status: 'Emerging' }]
  },
  {
    id: '11',
    title: 'Digital Literacy Gaps in Aging Workforce',
    summary: 'Workers over 45 facing rapid displacement due to inability to interact with AI-driven tools.',
    category: 'Education',
    location: 'North America / Japan',
    severity: 'High',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 94,
    rootCause: 'Rapid pace of tech change vs. slow corporate training cycles.',
    whoIsAffected: 'Late-career professionals.',
    whyItMatters: 'Causes massive economic displacement and loss of experience.',
    impactScore: 78,
    trend: [30, 45, 60, 78],
    thresholdLevel: 72,
    affectedPopulation: '65M',
    upvotes: 750,
    comments: [],
    solutionIdeas: ['Bite-sized micro-skilling', 'Low-code workshops'],
    tags: ['Jobs', 'AI', 'Lifelong Learning'],
    timestamp: '2025-11-18T11:00:00Z',
    stakeholders: [{ name: 'Global Skill Corp', type: 'Expert', role: 'Training', responseTime: '2h' }],
    timeline: [{ date: '2024-05-01', event: 'Upskilling gap detected', status: 'Escalating' }]
  },
  {
    id: '12',
    title: 'Early Childhood Education Deficit in Refugee Camps',
    summary: 'Lack of formal cognitive development programs for children aged 3-6 in transient settlements.',
    category: 'Education',
    location: 'Middle East / North Africa',
    severity: 'High',
    lifecycle: 'Emerging',
    credibility: 'Verified',
    credibilityScore: 90,
    rootCause: 'Resource prioritization for food and shelter over education.',
    whoIsAffected: 'Displaced children.',
    whyItMatters: 'Permanent loss of potential and systemic trauma.',
    impactScore: 85,
    trend: [40, 55, 70, 85],
    thresholdLevel: 80,
    affectedPopulation: '4M',
    upvotes: 1500,
    comments: [],
    solutionIdeas: ['App-based offline learning', 'Volunteer-led playgroups'],
    tags: ['Refugees', 'Human Rights', 'Children'],
    timestamp: '2025-11-20T09:30:00Z',
    stakeholders: [{ name: 'UNICEF', type: 'Expert', role: 'Strategic support', responseTime: '1h' }],
    timeline: [{ date: '2024-06-15', event: 'Field report verified', status: 'Emerging' }]
  },

  // TECHNOLOGY
  {
    id: '13',
    title: 'Algorithmic Bias in Automated Hiring',
    summary: 'Standard HR AI tools found to systematically penalize candidates from specific zip codes.',
    category: 'Technology',
    location: 'Global / Remote',
    severity: 'High',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 87,
    rootCause: 'Biased historical training data sets.',
    whoIsAffected: 'Job seekers in minority neighborhoods.',
    whyItMatters: 'Hardcodes social inequality into technology.',
    impactScore: 72,
    trend: [40, 52, 65, 72],
    thresholdLevel: 65,
    affectedPopulation: '200M+',
    upvotes: 890,
    comments: [],
    solutionIdeas: ['Ethical AI audits', 'Diverse synthetic training data'],
    tags: ['Ethics', 'AI', 'Equality'],
    timestamp: '2025-11-15T15:20:00Z',
    stakeholders: [{ name: 'FairHire AI', type: 'Startup', role: 'Solutions', responseTime: '12h' }],
    timeline: [{ date: '2024-04-15', event: 'Bias research published', status: 'Escalating' }]
  },
  {
    id: '14',
    title: 'Critical Vulnerability in Legacy Infrastructure',
    summary: 'Decades-old water management systems lack basic encryption, exposing them to remote hacking.',
    category: 'Technology',
    location: 'Western Europe / Oceania',
    severity: 'Critical',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 99,
    rootCause: 'Delayed modernization and lack of cybersecurity budget.',
    whoIsAffected: 'Urban populations reliant on utility grids.',
    whyItMatters: 'Potential for catastrophic service shutdown.',
    impactScore: 94,
    trend: [60, 75, 88, 94],
    thresholdLevel: 90,
    affectedPopulation: '45M',
    upvotes: 2100,
    comments: [],
    solutionIdeas: ['Hardened IoT gateways', 'Zero-trust architecture'],
    tags: ['Cybersecurity', 'Safety', 'Utilities'],
    timestamp: '2025-11-25T17:00:00Z',
    stakeholders: [{ name: 'Cyber Defense Force', type: 'Government', role: 'Security', responseTime: '0.1h' }],
    timeline: [{ date: '2024-06-01', event: 'Security audit failure', status: 'Escalating' }]
  },
  {
    id: '15',
    title: 'Satellite Debris "Kessler Syndrome" Risk',
    summary: 'Rapid increase in low-earth orbit debris threatens future space missions and global comms.',
    category: 'Technology',
    location: 'Orbital Space',
    severity: 'Critical',
    lifecycle: 'Emerging',
    credibility: 'Verified',
    credibilityScore: 98,
    rootCause: 'Unregulated satellite launches and lack of disposal plans.',
    whoIsAffected: 'Global communication systems.',
    whyItMatters: 'Could render space inaccessible for centuries.',
    impactScore: 91,
    trend: [30, 45, 60, 75, 91],
    thresholdLevel: 85,
    affectedPopulation: 'Global',
    upvotes: 3400,
    comments: [],
    solutionIdeas: ['Orbital cleanup harpoons', 'Self-deorbiting magnets'],
    tags: ['Space', 'Innovation', 'Environment'],
    timestamp: '2025-11-28T06:00:00Z',
    stakeholders: [{ name: 'Space Agency X', type: 'Expert', role: 'Monitoring', responseTime: '2h' }],
    timeline: [{ date: '2024-07-01', event: 'Debris collision peak', status: 'Emerging' }]
  },

  // ECONOMY
  {
    id: '16',
    title: 'Inflation-Driven SMEs Bankruptcy Spike',
    summary: 'Rising energy and material costs causing 15% closure rate of small local businesses.',
    category: 'Economy',
    location: 'Northern Hemisphere',
    severity: 'High',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 93,
    rootCause: 'Geopolitical instability and energy supply constraints.',
    whoIsAffected: 'Small business owners and local employees.',
    whyItMatters: 'Erosion of local community resilience.',
    impactScore: 84,
    trend: [40, 58, 72, 84],
    thresholdLevel: 78,
    affectedPopulation: '18M Businesses',
    upvotes: 1200,
    comments: [],
    solutionIdeas: ['Community-backed lending', 'Energy cooperatives'],
    tags: ['Local Biz', 'Energy', 'Policy'],
    timestamp: '2025-11-20T11:00:00Z',
    stakeholders: [{ name: 'Economic Recovery Unit', type: 'Government', role: 'Subsidy', responseTime: '72h' }],
    timeline: [{ date: '2024-05-15', event: 'Bankruptcy peak noted', status: 'Escalating' }]
  },
  {
    id: '17',
    title: 'Gig Economy Health Insurance Gap',
    summary: '85% of gig workers lack affordable health coverage due to outdated labor laws.',
    category: 'Economy',
    location: 'Global / Urban Hubs',
    severity: 'Medium',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 89,
    rootCause: 'Classification of workers as independent contractors.',
    whoIsAffected: 'Delivery, ride-share, and freelance workers.',
    whyItMatters: 'Creates a massive public health and financial risk.',
    impactScore: 68,
    trend: [40, 52, 60, 68],
    thresholdLevel: 55,
    affectedPopulation: '350M',
    upvotes: 2300,
    comments: [],
    solutionIdeas: ['Portable benefit accounts', 'Worker-owned insurance co-ops'],
    tags: ['Labor', 'Health', 'Future of Work'],
    timestamp: '2025-11-10T14:00:00Z',
    stakeholders: [{ name: 'Gig Union Alliance', type: 'NGO', role: 'Advocacy', responseTime: '12h' }],
    timeline: [{ date: '2024-04-10', event: 'Policy debate starts', status: 'Escalating' }]
  },
  {
    id: '18',
    title: 'Housing Affordability in "Second-Tier" Cities',
    summary: 'Rapid remote-work migration causing 25% rent hikes in previously affordable medium-sized cities.',
    category: 'Economy',
    location: 'North America / Europe',
    severity: 'High',
    lifecycle: 'Escalating',
    credibility: 'Verified',
    credibilityScore: 95,
    rootCause: 'Supply shortage vs. sudden high-income influx.',
    whoIsAffected: 'Local middle-to-low income residents.',
    whyItMatters: 'Forces locals out and destroys local culture.',
    impactScore: 80,
    trend: [50, 65, 72, 80],
    thresholdLevel: 75,
    affectedPopulation: '120M',
    upvotes: 4500,
    comments: [],
    solutionIdeas: ['Adaptive reuse of offices', 'Vacancy taxes'],
    tags: ['Housing', 'Urbanism', 'Inequality'],
    timestamp: '2025-11-22T10:00:00Z',
    stakeholders: [{ name: 'City Planning Board', type: 'Government', role: 'Zoning', responseTime: '48h' }],
    timeline: [{ date: '2024-06-01', event: 'Market report released', status: 'Escalating' }]
  }
];
